export enum EErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  PLAYER_NOT_FOUND = 'PLAYER_NOT_FOUND',
  INVALID_PHASE = 'INVALID_PHASE',
  NOT_YOUR_TURN = 'NOT_YOUR_TURN',
  INVALID_ACTION = 'INVALID_ACTION',
  INVALID_FREE_ACTION = 'INVALID_FREE_ACTION',
  INVALID_INPUT_RESPONSE = 'INVALID_INPUT_RESPONSE',
  INSUFFICIENT_RESOURCES = 'INSUFFICIENT_RESOURCES',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export interface IErrorPayload {
  code: EErrorCode;
  message: string;
  details?: Record<string, unknown>;
}
