export enum EPriority {
  COST = 0,
  ROTATION,
  CORE_EFFECT,
  IMMEDIATE_REWARD,
  CARD_TRIGGER,
  SECTOR_COMPLETION,
  DEFAULT,
  HAND_LIMIT,
  END_OF_ROUND_CARD,
  MILESTONE,
  DISCOVERY,
  TURN_HANDOFF,
}
